#!/bin/bash
echo "START ardoprun ${0}"

AUDIOIN=plughw:1,0
AUDIOIN=plughw:2,0
AUDOOUT=${AUDIOIN}

#CAT=
#DEVICE=/dev/ttyUSB0

arecord -l

#piardopc 8515 plughw:1,0 plughw:1,0 #--cat ${DEVICE} -k TX1; -u TX0; 

echo piardopc 8515 ${AUDIOIN} ${AUDOOUT}
piardopc 8515 ${AUDIOIN} ${AUDOOUT}
