#!/bin/bash
echo "START       $(date -u +%y-%m-%d_%H%Mz)"


#Gateway Channel Information
#Callsign:	VE3HJL
#Frequency:	7108.000 KHz
#Frequency:	3611.000 KHz
#Frequency:	3600.000 KHz
#Gridsquare:	FN03IR
#Antenna:	Omni
#Operating Mode:	ARDOP / ARDOP 2000
#Operating Hours:	10-22
#Last Status Received:	2020-01-11 01:35 -05:00
#Comments:	Sponsored by the Toronto Ares and Emergency Communications Ontario Association Inc.

FREQ=7106500
FREQ=3609500
FREQ=3598500

#Gateway Channel Information
#Hybrid network participant — forwards traffic automatically via RF
#Callsign:	KC8YJJ
#Frequency:	3589.500 KHz
#Frequency:	7102.500 KHz
#Gridsquare:	EN90PL
#Antenna:	Omni
#Operating Mode:	ARDOP / ARDOP 2000
#Operating Hours:	00-23
#Last Status Received:	2020-01-11 03:08 -05:00
#Comments:

#FREQ=7100500
#FREQ=3588000
#FREQ=3589500


#/usr/bin/killall arecord
#echo "CHANGE MODE $(date -u +%y-%m-%d_%H%Mz)"
#/data/bin/yaesuctl M LSB 2400
#echo "CHANGE FREQ $(date -u +%y-%m-%d_%H%Mz)"
/data/bin/yaesuctl F ${FREQ} M PKTUSB 1500
#echo "RECORDING   $(date -u +%y-%m-%d_%H%Mz)"

NET=ve3HJL

LOC=/data/record/recordings/${NET}/

FNAME="${LOC}${NET}$(date -u +%y-%m-%d_%H%Mz).wav"

#LOC=/data/record/${NET}/

#cd ${LOC}

PIDFILE="/tmp/${NET}.pid"
#echo $FNAME
#exit
#arecord -d 1800 --process-id-file ${PIDFILE} -D plughw:CARD=CODEC,DEV=0  -t wav --max-file-time 1802 $FNAME 
#chmod g+w $FNAME
#sleep 1

#PID=`cat ${PIDFILE}`
#
#sleep 1800
#
#kill -2 ${PID}

yaesuctl f m
