#!/bin/bash

AUDIOIN=plughw:1,0
AUDIOIN=plughw:2,0
AUDOOUT=${AUDIOIN}

CAT=
DEVICE=/dev/ttyUSB0

echo piardopc 8515 ${AUDIOIN} ${AUDOOUT} 
piardopc 8515 ${AUDIOIN} ${AUDOOUT} #--cat ${DEVICE} -k TX1; -u TX0; 
